### ISSUE TITLE
Trying to set up planetscale with the code. syntax error on Seed

### ISSUE THREAD

**Issue by rauf543** [MathiasGruber/TheNinjaRPG#181]
I've set up the environment locally with the planetscale imitation, but it works extremely slowly, extremely slowly, I thought transferring the db over to an actual planetscale instance would make things more bearable for local testing. However, once I have updated the db_url in the env file the make dbpush goes through successfully, however, I am stuck at make seed, I get the following error:

`vscode ➜ /workspace (main ✗) $ make seed
Run drizzle db seed 
docker exec -it tnr_app pnpm seed

> tnr@0.1.0 seed /workspace/app
> pnpm tsx drizzle/seed.ts

Clearing old jutsus...
Syncing jutsus...
DatabaseError: syntax error at position 251654 near 'INSERT'
    at Connection.execute (file:///workspace/app/node_modules/.pnpm/@planetscale+database@1.16.0/node_modules/@planetscale/database/dist/index.js:89:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PlanetScalePreparedQuery.execute (/workspace/app/node_modules/.pnpm/drizzle-orm@0.33.0_@opentelemetry+api@1.9.0_@planetscale+database@1.16.0_@types+pg@8.6.1_@typ_vln47xtz7ynqsl55ksuzpajx54/node_modules/src/planetscale-serverless/session.ts:58:16)
    at seedJutsus (/workspace/app/drizzle/seeds/jutsu.ts:12:3)
    at main (/workspace/app/drizzle/seed.ts:13:3) {
  status: 400,
  body: {
    message: "syntax error at position 251654 near 'INSERT'",
    code: 'UNKNOWN'
  }
}
 ELIFECYCLE  Command failed with exit code 1.
make: *** [Makefile:60: seed] Error 1`

Not that experienced with these technologies so would appreciate any help

**Comment by rauf543** [comment]
Adding more info:

Most probably related to the way I am trying to set-up planetscale, I get the DATABASE_URL from the connection type "Node.js", and have the MYSQL_URL as the same

Example:

```
# Replace placeholder values with your actual credentials
DATABASE_URL='mysql://<USERNAME>:<PASSWORD>@<HOST>/<DATABASE>?ssl={"rejectUnauthorized":true}'
```

**Comment by MathiasGruber** [comment]
I'll look into it :)

**Comment by MathiasGruber** [comment]
Should be fixed with latest PR - seems like the queries in seed files had to be split to be run one at a time. Let me know if it's better - it should actually be faster with the local database, but overall I'd love to improve the development setup to be faster; the current codebase size is making things a bit slow to work with :/ .. so far my attempts to use e.g. turbo have not been fruitful.
